---
title: Estatística em Psicologia 
author: Gilberto Pereira Sassi
date: Primeiro semestre de 2023
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
---

## Cronograma

[Cronograma de atividades por semana](cronograma-matc65.xlsx)

## Slides

### Primeiro dia de aula 

[Primeiro dia](primeiroDia-matc65.pdf)

### Estatística descritiva

* [Gráficos](graficos.pdf)
* [Medidas de resumo](medidasResumo.pdf)

### Probabilidade

* [Introdução à probabilidade](introProb.pdf)
* [Variável aleatória contínua](varContinua.pdf)
* [Variável aleatória discreta](varDiscreta.pdf)

### Intervalo de confiança: uma população

[Intervalo de confiança: uma população](intervaloConfianca.pdf)

### Teste de hipóteses: uma população

[Teste de hipóteses: uma população](testeHipoteses.pdf)

### Teste de hipóteses: duas populações

[Teste de hipóteses: duas populações](testeHipoteses2pop.pdf)

### Regressão linear simples

[Regressão linear simples](regressao-linear-simples.pdf)

## Listas de exercícios

* [Lista 1](lista_est_descr.pdf)
* [Lista 2](lista_prob.pdf)
* [Lista 3](lista-ex-ic.pdf)
* [Lista 4](lista-test-1-pop.pdf)
* [Lista 5](lista-test-2-pop.pdf)
* [Lista 6](lista-regressao-simples.pdf)

## Gravações de dois anos atrás

Gravações de aula durante o período de pandemia de dois anos atrás está no link [gravação de dois anos atrás](https://bit.ly/gravacao_matc65_2022_1). Gostaria de te alertar que a maneira como eu explico os conteúdos no formato on-line há dois anos atrás pode não ser a mesma forma que eu explico os conteúdos hoje no formato presencial.


## Conjunto de dados

[`empresa_XXX.xlsx`](empresa_XXX.xlsx)

## Referências

[Applied Statistics and Probability for Engineers](applied-statistics-montgomery.pdf)<br>
[Estatística Aplicada às Ciências Sociais](estatistica-aplicada-barbetta.pdf)<br>
[Estatśitica Básica](estatistica-basica-bussab-morettin.pdf)<br>
[Applied Statistics for Civil and Environmental Engineers](kottegoda.pdf)


## Número de faltas

[Número de faltas](https://ufbabr-my.sharepoint.com/:x:/g/personal/gilberto_sassi_ufba_br/EciKwlH0DV9EgxH8bZIuZu0BxnPekCp3hg6LjxWv8HMbHA?e=w7Qf38){target="_blank"}