---
title: Estatística em Psicologia 
author: Gilberto Pereira Sassi
date: Primeiro semestre de 2022
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
---

## Cronograma

[Cronograma de atividades por semana.](cronograma-matc65.xlsx)

## Conjunto de dados

* [`companhia_MB.xlsx`](companhia-mb.xlsx)

## Tabelas

* [Tabela da distribuição normal](tabela-z.pdf)
* [Tabela da distribuição t-Student](tabela-t-student.pdf)
* [Tabela da distribuição qui-quadrado](tabela-chi-square.pdf)

## Slides e materiais

### Primeiro dia de aula

[Primeiro dia de aula](primeirodia.pdf)

### Unidades 1, 2 e 3

* [Slides - tabelas e gráficos](graficos.pdf)
* [Slides - medidas de Resumo](medidasresumo.pdf)
* [Lista de exercícios](lista-est-descr.pdf)

### Unidade 4

* [Slides - probabilidade](introprob.pdf)
* [Slides - variável contínua](varcontinua.pdf)
* [Slides - variável discreta](vardiscreta.pdf)
* [Lista de exercícios](lista-prob.pdf)

### Unidade 5

* [Slides - intervalo de confiança](intervaloconfianca.pdf)
* [Slides - teste de hipóteses para uma população](testehipoteses.pdf)
* [Lista de exercícios - intervalo de confiança](lista-ex-ic.pdf)
* [Lista de exercícios - teste de hipóteses - parte 1](lista-test-1-pop.pdf)
* [Lista de exercícios - teste de hipóteses - parte 2](lista-test-1-pop-part2.pdf)

## Notas de aulas, panilhas e backup de gravações

As notas de aula, as planilhas do _google docs_ e os _backup_ das gravações estão armazenadas em repositório do _Google Drive_ que você pode acessar pelo link: [Arquivos -- MATC65 Estatística em Psicologia](https://cutt.ly/arquivos-matc65-2022-1sem).

## Nota do Fórum

* [Semana de 13/03/2022 a 19/03/2022](mes-3-dia-13-ava-matc65.xlsx)
* [Semana de 20/03/2022 a 26/03/2022](mes-3-dia-20-ava-matc65.xlsx)