---
title: Análise Descritiva e Exploratória de Dados A - MATD39
author: Gilberto Pereira Sassi
date: Segundo semestre de 2023
output:
  html_document:
    theme: readable
    highlight: kate
    toc: true
    toc_float: true
---

## Cronograma

[Cronograma - Análise Descritiva e Exploratória de Dados A - MATD39](cronograma-matd39.xlsx)

## Servidor no discord

Toda a nossa comunicação será realizada pelo discord chamado _estatísticos_. Entre no servidor usando o seguinte link: [estatísticos](https://discord.gg/48u3s5JcrA).

## Slides

[Primeiro dia de aula](primeiro-dia-matd39.pdf){target="_blank"}<br>
[Exploração e visualização de dados](exploracao-visualizacao.pdf){target="_blank"}

## Conjunto de dados

[arquivos - Exploração e visualização de dados](arquivos.zip)

---

Como explicado em sala de aula, cada estudante vai analisar uma amostra de candidatos do ENEM de 2022 em específica cidade (olhe na tabela abaixo). Em sua cidade, a/o estudante vai verificar se raça (`tp_cor_raca`) e/ou tipo de escola (`tp_escola`) _exercem influência_ na nota de matemática (`nu_nota_mt`).

```{r}
#| echo: false
#| message: false
library(readxl)
library(glue)
library(tidyverse)

set.seed(12345)

df_estudantes <- read_xlsx("matd39-inscritos.xlsx")
df_cidades <- read_xlsx("maiores-cidades-br.xlsx")
df_cidades <- sample_n(df_cidades, nrow(df_estudantes))

col_csv <- seq_len(nrow(df_cidades)) |>
  map_chr(\(k) {
    glue("[{df_cidades$cidade[k]}]({df_cidades$apelido[k]}.csv)")
  })
col_xlsx <- seq_len(nrow(df_cidades)) |>
  map_chr(\(k) {
    glue("[{df_cidades$cidade[k]}]({df_cidades$apelido[k]}.xlsx)")
  })



df_tab <- cbind(
  df_cidades |> select(-apelido),
  col_csv, col_xlsx,
  df_estudantes$matricula, df_estudantes$nome |> str_to_title()
) |>
  rename(
    Cidade = cidade, UF = estado,
    "Arquivos .csv" = "col_csv",
    "Arquivos .xlsx" = "col_xlsx",
    Matricula = "df_estudantes$matricula",
    Nome = "str_to_title(df_estudantes$nome)"
  )

knitr::kable(df_tab, caption = "Conjunto de dados de cada estudante com amostras de candidatos do ENEM 2022 para cidades do Brasil.")
```

## Primeiro dia de aula

O critério de avaliação, datas das provas e demais informações foram divulgadas no primeiro dia de aula. Estas informações estão nos slides usados, que você pode acessar pelo seguinte link: [primeiro dia de aula](primeiro-dia-matd39.pdf){target="_blank"}.

## Referências

[Estatística básica](estatistica-basica-bussab-morettin.pdf){target="_blank"}<br>
[Applied statistics and probability for engineers](applied-statistics-montgomery.pdf){target="_blank"}<br>
[`R` for Data Science](https://r4ds.hadley.nz/){target="_blank"}<br>
[`python` for Data Analysis](https://wesmckinney.com/book/){target="_blank"}<br>
[`rmarkdown`: The definitive guide](https://bookdown.org/yihui/rmarkdown/){target="_blank"}<br>
[`quarto` documentation](https://quarto.org/docs/guide/){target="_blank"}