---
title: Análise Descritiva e Exploratória de Dados A - MATD39
author: Gilberto Pereira Sassi
date: "2023/08/01"
date-format: "[Segundo semestre de] YYYY"
lang: pt-BR
format:
  html:
    theme: simplex
    highlight-style: kate
    embed-resources: true
    anchor-sections: true
    toc: true
    toc-location: left
---

## Cronograma

[Cronograma - Análise Descritiva e Exploratória de Dados A - MATD39](cronograma-matd39.xlsx)

## Notas 

[Notas finais (atualizado no dia 07/12/2023)](https://docs.google.com/spreadsheets/d/1hiLlToDZAHwBLM2yDY1PhQHuf1j-SmHv3faQ6cWcCXo/edit?usp=sharing){target="_blank"}

## Servidor no discord

Toda a nossa comunicação será realizada pelo discord chamado _estatísticos_. Entre no servidor usando o seguinte link: [estatísticos](https://discord.gg/48u3s5JcrA).

## Slides

[Primeiro dia de aula](primeiro-dia-matd39.pdf){target="_blank"}<br>
[Exploração e visualização de dados](exploracao-visualizacao.pdf){target="_blank"}<br>
[`rmarkdown` e `quarto`](rmarkdown-quarto.pdf){target="_blank"}<br>
[Introdução à linguagem `R`](linguagem-r.pdf){target="_blank"}

## Conjunto de dados

[Conjuntos de dados](conjunto_dados.zip)

## Código

[Aula no laboratório até o dia 31/08/2023](arquivos.zip){target="_blank"}<br>
[Aula do dia 31/08/2023](https://docs.google.com/spreadsheets/d/15yqfrpXLJKrmu-RLDT8OWUBgH8PK1QRlv1wRjdrO8SQ/edit?usp=sharing){target="_blank"}<br>
[Aula do dia 14/09/2023](https://docs.google.com/spreadsheets/d/1Kpa5sFp0350MPFVsbrVYCfLRyq1ZT1fo3so5biFuizQ/edit?usp=sharing){target="_blank"}<br>
[Aula do dia 08/11/2023 (`rmarkdown` + `html`)](aula_dia_2023_11_08.zip)

### `codeshare.io`

[Aula de segunda e quarta](https://codeshare.io/mpwBxb){target="_blank"}<br>
[Aula de terça-feira](https://codeshare.io/DZON3r){target="_blank"}<br>
[Markdown + $\LaTeX$](https://codeshare.io/JboZzd){target="_blank"}<br>
[Rmarkdown - `HTML`](https://codeshare.io/OdMwBx){target="_blank"}

### aula do dia 06/09/2023

[`renda.R`](renda-2023-09-05.R)<br>
[`atividade_semanal.R`](atividade_semanal-2023-09-05.R)

### Quarto ([**`codeshare.io`**](https://codeshare.io/){target="_blank"})

Abaixo estão listados o código para produzir documento usando [quarto.org](https://quarto.org/){target="_blank"}:

* [`pdf`](https://gist.github.com/gilberto-sassi/e9642d62c42531de212187258bc078a6){target="_blank"}
* [`html`](https://gist.github.com/gilberto-sassi/050ed601f35ce988ad02d82572e38586){target="_blank"}
* [`apresentação beamer`](https://gist.github.com/gilberto-sassi/58b5f3adbbe7b9bd160100d8e8f02854){target="_blank"}
* [`Website`](https://github.com/gilberto-sassi/website-matd39.git){target="_blank"}: este website está hospeado em [matd39.netlify.app](https://matd39.netlify.app){target="_blank"}

Matriz de modelos e cores: [matriz de estilo para `beamer`](https://mpetroff.net/files/beamer-theme-matrix/){target="_blank"}.


### Gravação de parte da aula do dia 06/09/2023

Nesta gravação, mostro como trabalhar com a variável `q006` do conjunto de dados do ENEM na edição de 2022.

{{< video https://youtu.be/Q8Twlxp8kMs?si=8w9JmhjePbAcW5hq >}}

---

## _datasets_ da sala de aula
Como explicado em sala de aula, cada estudante vai analisar uma amostra de candidatos do ENEM de 2022 em específica cidade (olhe na tabela abaixo). Em sua cidade, a/o estudante vai verificar se raça (`tp_cor_raca`) e/ou tipo de escola (`tp_escola`) _exercem influência_ na nota de matemática (`nu_nota_mt`).

As variáveis dos _datasets_ estão explicadas em [dicionário microdados - ENEM 2022](dicionario_enem_2022.xlsx).

```{r}
#| echo: false
#| message: false
library(readxl)
library(glue)
library(tidyverse)

set.seed(12345)

df_estudantes <- read_xlsx(glue("matd39-inscritos.xlsx"))
df_cidades_raw <- read_xlsx(glue("maiores-cidades-br.xlsx"))
df_cidades <- sample_n(df_cidades_raw, nrow(df_estudantes))

col_csv <- seq_len(nrow(df_cidades)) |>
  map_chr(\(k) {
    glue("[{df_cidades$cidade[k]}]({df_cidades$apelido[k]}.csv)")
  })
col_xlsx <- seq_len(nrow(df_cidades)) |>
  map_chr(\(k) {
    glue("[{df_cidades$cidade[k]}]({df_cidades$apelido[k]}.xlsx)")
  })

df_tab <- cbind(
  df_cidades |> select(-apelido),
  col_csv, col_xlsx,
  df_estudantes$matricula, df_estudantes$nome |> str_to_title()
) |>
  rename(
    Cidade = cidade, UF = estado,
    "Arquivos .csv" = "col_csv",
    "Arquivos .xlsx" = "col_xlsx",
    Matricula = "df_estudantes$matricula",
    Nome = "str_to_title(df_estudantes$nome)"
  )

# inclusão de eduarda
`%notin%`  <- \(x, y) !(x %in% y)
df_estudantes_eduarda <- read_xlsx(glue("lista_frequencia_matd39.xlsx"))
df_estudantes_eduarda <- df_estudantes_eduarda |>
  filter(email %notin% df_estudantes$email)
df_cidades_eduarda <- read_xlsx(glue("maiores-cidades-br.xlsx"))
df_cidades_eduarda <- df_cidades_eduarda |>
  filter(apelido %notin% df_cidades$apelido)
df_cidades_eduarda <- sample_n(df_cidades_eduarda, nrow(df_estudantes_eduarda))

col_csv <- seq_len(nrow(df_cidades_eduarda)) |>
  map_chr(\(k) {
    glue("[{df_cidades_eduarda$cidade[k]}]({df_cidades_eduarda$apelido[k]}.csv)")
  })
col_xlsx <- seq_len(nrow(df_cidades_eduarda)) |>
  map_chr(\(k) {
    glue("[{df_cidades_eduarda$cidade[k]}]({df_cidades_eduarda$apelido[k]}.xlsx)")
  })

df_tab_eduarda <- cbind(
  df_cidades_eduarda |> select(-apelido),
  col_csv, col_xlsx,
  df_estudantes_eduarda$matricula,
  df_estudantes_eduarda$nome |> str_to_title()
) |>
  rename(
    Cidade = cidade, UF = estado,
    "Arquivos .csv" = "col_csv",
    "Arquivos .xlsx" = "col_xlsx",
    Matricula = "df_estudantes_eduarda$matricula",
    Nome = "str_to_title(df_estudantes_eduarda$nome)"
  )

# inclusão de gilberto
df_tab_gilberto <- tibble(
  Cidade = "Salvador",
  UF = "BA",
  `Arquivos .csv` = "[Salvador](salvador.csv)",
  `Arquivos .xlsx` = "[Salvador](salvador.xlsx)",
  Matricula = 1297159,
  Nome = "Gilberto Pereira Sassi"
)

df_tab_final <- rbind(
  df_tab,
  df_tab_eduarda,
  df_tab_gilberto
) |>
  arrange(Nome)

# imprimindo a tabela na página
knitr::kable(df_tab_final, caption = "Conjunto de dados de cada estudante com amostras de candidatos do ENEM 2022 para cidades do Brasil.")
```

## Primeiro dia de aula

O critério de avaliação, datas das provas e demais informações foram divulgadas no primeiro dia de aula. Estas informações estão nos slides usados, que você pode acessar pelo seguinte link: [primeiro dia de aula](primeiro-dia-matd39.pdf){target="_blank"}.

## Referências

[Estatística básica](estatistica-basica-bussab-morettin.pdf){target="_blank"}<br>
[Applied statistics and probability for engineers](applied-statistics-montgomery.pdf){target="_blank"}<br>
[`R` for Data Science](https://r4ds.hadley.nz/){target="_blank"}<br>
[`python` for Data Analysis](https://wesmckinney.com/book/){target="_blank"}<br>
[`rmarkdown`: The definitive guide](https://bookdown.org/yihui/rmarkdown/){target="_blank"}<br>
[`quarto` documentation](https://quarto.org/docs/guide/){target="_blank"}